[profile.default]
src = "contracts"
out = "out"
test = "test"
libs = ["dependencies"]

solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"

[profile.default.fmt]
sort_imports = true
contract_new_lines = true
bracket_spacing = true

[profile.default.lint]
lint_on_build = true
ignore = [ "test/**/*" ]
exclude_lints = [ "mixed-case-function", "mixed-case-variable", "pascal-case-struct" ]

[soldeer]
remappings_regenerate = false

[dependencies]
forge-std = "1.12.0"
"@openzeppelin-contracts" = "5.5.0"
"@openzeppelin-contracts-upgradeable" = "5.5.0"
onchain-id = { version = "2.2.2-beta3", git = "https://github.com/onchain-id/solidity.git", tag = "2.2.2-beta3" }

[rpc_endpoints]
baseSepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"

